#
#   Builds the Packages for a given release
#

on:
  push:
    tags: 
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Build Release

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Exit if not on podbuilder branch
        if: endsWith(github.ref, 'podbuilder') == false
        run: |
          echo ref: '${{ github.ref }}'
          exit -1

      - name: Build Packages
        run: |
          echo ref: '${{ github.ref }}'
          echo ref_name: '${{ github.ref_name }}'
          cd scripts/podbuilder
          ./build.sh all

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          #automatic_release_tag: "latest"
          files: |
            scripts/podbuilder/*.rpm
            #scripts/podbuilder/*.deb


