#
#   Builds the Packages for a given release
#

on:

  push:

    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

    # Only on podbuilder branch - we have no Github CI anywhere else (yet)
    branches: [ podbuilder ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Build Release

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Packages
        run: |
          echo ref: '${{ github.ref }}'
          echo ref_name: '${{ github.ref_name }}'
          cd scripts/podbuilder
          ./build.sh all

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            scripts/podbuilder/*.rpm
            scripts/podbuilder/*.deb


