
#
#  This follows an example in https://github.com/docker/metadata-action and some earlier versions of videorock
#

name: Docker Image Build and Push

on:
  push:
    tags:
      - 'alpine-dev/v[0-9]+.[0-9]+.[0-9]+'
      # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags for details

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/mistserver-alpine-dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=alpine-dev/v(.*),group=1
            type=match,pattern=alpine-dev/v(\d+\.\d+)\.*,group=1
          # see https://github.com/docker/metadata-action?tab=readme-ov-file#typematch for details

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
